presence.config.catalog = {
  "@all_languages": "yes",
  "language": "English",
  "buddyListTitle": "Chat",
  "buddyListTitle_min": "Chat ",
  "followed": "People I Follow",
  "groups": "Groups",
  "notFollowing": "Not Following",
  "options": "Options",
  "addBtn": "Add",
  "available": "Available",
  "idle": "Idle",
  "away": "Away",
  "unavailable": "Offline",
  "options_inactive": "Change status to Idle after",
  "options_offline_people": "Show people who are offline",
  "options_offline_groups": "Hide offline groups",
  "noBuddies": "No one is available to chat.",
  "tryRec": "Try reconnecting",
  "tryAgain": "Try again?",
  "widgetLoading": "Connecting...",
  "WidgetLoadFailed": "Unable to connect to chat.",
  "messageAlert": "Chat Message!",
  "New": "New",
  "selfMsg": "Me",
  "MsgDeliveryErr": "Your message couldn't be sent.",
  "add": "Invite",
  "details": "in chat",
  "detailsHeader": "Participants",
  "detailsReInvite": "Add again",
  "composingTxt": "{%1%} is typing...",
  "userAdded": "{%1%} joined the chat. ",
  "userAddedUser": "{%1%} added {%2%} to this chat. ",
  "userLeft": "{%1%} left the chat. ",
  "followText": "Follow {%1%}",
  "followTextTip": "People you follow in Chatter are in your Chat list.",
  "followingText": "You're now following {%1%}.",
  "searchDefaultText": "Find people...",
  "sendingMsg": "Sending message...",
  "subspacefailed": "Problem in chat session.",
  "addMembersFailed": "Couldn't add {%1%} to chat.",
  "removeMembersFailed": "Couldn't remove {%1%} from chat.",
  "msgTryAgain": "Try sending now.",
  "inviteHeader": "Add Participants",
  "typeToAddUser": "Add people to chat...",
  "noResult": "No matching names.",
  "chatTextExceeded": "{%1%} characters over the {%2%} character limit.",
  "offlineWentMsg": "{%1%} is offline.",
  "idleWentMsg": "{%1%} is idle.",
  "awayWentMsg": "{%1%} is away.",
  "onlineWentMsg": "{%1%} is available.",
  "maxUsersExceed": "Limit: {%1%} participants",
  "months":   [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ],
  "Disconnected": "Not connected",
  "userRemoved": "You left the chat.",
  "AM": "AM",
  "PM": "PM",
  "TodayAt": "Today at {%1%}",
  "YesterdayAt": "Yesterday at  {%1%}",
  "SomedayAt": "{%1%} at {%2%}",
  "FeedbackLink": "Feedback?",
  "groupMuted": "This group can't chat with you.",
  "groupMutedDesc": "To let this group chat with you, click the group name and start a chat.",
  "groupUnMuted": "This group can chat with you.",
  "groupUnMutedDesc": "To block this group from chatting with you, click Options | Chatter Groups.",
  "userAddedBack": "You joined the chat.",
  "availableMembers": "Available Members",
  "Loading": "Loading...",
  "FindPeopleNGroups": "Find people or groups...",
  "RemoveFromChat": "Remove {%1%} from this chat.",
  "ConnectionFailed": "Not connected",
  "Close": "Close",
  "Minimize": "Minimize",
  "Open": "Restore",
  "PopOutChat": "Pop out",
  "PopInChat": "Pop in",
  "Preferences": "Options",
  "PreferencesMenuText": "Options...",
  "General": "General Settings",
  "Notifications": "Sounds and Notifications",
  "ChatterGroups": "Chat List",
  "Save": "Save",
  "Cancel": "Cancel",
  "RosterSettings": "Chat List Settings",
  "WindowSettings": "Chat Window Settings",
  "SetOffline": "Change status to Offline when Chat connects",
  "ShowEmoticons": "Show emoticons",
  "Minutes": "minutes",
  "NotificationSettings": "Notification Settings",
  "MessageBrowserTab": "Alert in browser tab for new messages",
  "PlayAudible": "Play a sound for new messages",
  "OpenChatWindows": "Minimize all incoming chat messages",
  "ChatterGroupSettings": "Chatter Group Settings",
  "Actions": "Action",
  "GroupName": "Chatter Group",
  "StopReceiving": "Stop receiving chat messages from this group",
  "StartReceiving": "Receive chat messages from this group",
  "Relogin": "Please log in again",
  "ReConnectInMinutes": "Re-connecting in {%1%} min",
  "ReConnectInSeconds": "Re-connecting in {%1%}s",
  "PageLeaveMessage": "If you leave, the chat won’t be saved.",
  "cantChat": "Right now, this group can't send you chat messages.",
  "cantChatDesc": "To chat with this group, enable the group to receive messages.",
  "enableGroupNow": "Enable group chat messages.",
  "popInConfirmMessage": "You can’t start a chat while chat is popped out. Do you want to pop in?",
  "EmptyGroups": "You're not a member of any Chatter groups.",
  "nobodyElseInChat": "No one in this group is available for group chat.",
  "DisconnectAlertText": "You're no longer signed in to Salesforce.",
  "LoginAlert": "Login Alert",
  "ok": "Ok",
  "Found": "{%1%} found",
  "You": "You",
  "Play": "Play",
  "Pause": "Pause",
  "ShowDeskNotification": "Show desktop notifications (Chrome only)",
  "hasSentYouMessage": "sent you a chat message",
  "FollowedGroups": "Find people or groups...",
  "leaveChat": "I want to leave",
  "minimizeChat": "Just minimize this chat",
  "leaveChatWarning": "If you leave this chat, people can keep chatting without you. You'll have to be added again to participate.",
  "conversations": "Current Chats",
  "Help": "Help",
  "ChatList": "Chat List",
  "DisplayTimeStamp": "Show a timestamp only when I hover over a message",
  "Status": "Status:",
  "Messages": "Messages:",
  "ShowLists": "Show these lists:",
  "SetNotifications": "Notifications",
  "Sounds": "Sounds",
  "FirstMessage": "New chats only",
  "EveryMessage": "Every message",
  "MuteAll": "Mute all sounds",
  "Hour": "Hour",
  "Hours": "Hours",
  "favourites": "My Favorites",
  "searchList": "Everyone",
  "pleaseAddFavorites": "Drag people's names here",
  "favorite": "Add to favorites",
  "RemoveFavorite": "Remove favorite",
  "edit": "Edit",
  "done": "Done",
  "removeFavorite": "Remove this favorite",
  "ShowChatList": "Show in chat list",
  "MyChatList": "My Favorites",
  "OfflineContacts": "Offline People",
  "PlaySounds": "Play sounds",
  "ShowEmoticonsMenu": "Show emoticons",
  "Search": "Search",
  "ClearSearch": "Clear search",
  "ChangeStatus": "Change your status",
  "RemoveConv": "Close Chat",
  "SavingPref": "Saving your changes…",
  "FailedSettings": "Your changes couldn’t be saved. Try again.",
  "EnterValidNum": "Type a number, in minutes, between 1 and 480 (8 hours).",
  "InstallFlash": "Adobe® Flash® Player is required.",
  "ChatWindowPopOutFailed": "The chat window didn't load correctly, so you won't be able to send messages or add others to the chat. Try popping the window in and out again.",
  "ReclaimChatWindow": "Error in adding the user to chat",
  "Collapse": "Collapse",
  "Expand": "Expand",
  "NewMessage": "New message",
  "DontShowMessageAgain": "Don't show this message again",
  "StartShare": "Start screen sharing",
  "StopShare": "Stop Share",
  "StartView": "Start View",
  "StopView": "Stop View",
  "UserScreen": "{%1%}  Screen  ",
  "View": "View ",
  "Viewing": "Viewing ",
  "PublisherStatus": "You're sharing your screen.",
  "PublisherStatusStopped": "You stopped sharing your screen.",
  "ShareInProgress": "You are already sharing your screen. Only one screen sharing session is allowed at a time.",
  "ViewerInProgress": "You are already viewing someone's screen. Only one screen sharing session is allowed at a time.",
  "ShareAlert": "Alert",
  "join": "join",
  "JavaNotInstalled": "Install Java version 1.6 or newer and then try again.",
  "Your": "your",
  "InternalError": "An internal screen sharing error occurred. Please try again.",
  "CantLeaveChat": "Screen sharing is in progress. Stop sharing your screen to leave the chat.",
  "EnterValidTimeout": "Type a number, in seconds, between 30 and 900 (15 minutes).",
  "EnterValidRetries": "Type a number, between 3 and 10. ",
  "ScreenSharing": "Screen Sharing",
  "OnAir": "On Air",
  "StartingShare": "Starting screen share",
  "Environmentcheck": "Checking Environment",
  "EnvcheckAdditionText": "May take up to 15 seconds",
  "StopSharing": "Stop screen sharing",
  "FailedToLoad": "An internal screen sharing error occurred. Please try again.",
  "Retry": "Retry",
  "InstallPlugin": "Installing screen share plug-in",
  "StartingSession": "Initiating session ",
  "Continue": "Continue ",
  "Sharing": "Sharing",
  "Stop": "Stop",
  "leaveQuestion": "Are you sure you want to stop sharing your screen? ",
  "ErrorOccured": "A screen sharing error occurred. Please try again.",
  "AnotherSession": "You are already in a screen sharing session. Only one screen sharing session is allowed at a time.",
  "ScreenSharingOptions": "Screen Sharing Options",
  "ConnectionTimeout": "Connection Timeout",
  "Retries": "Retries",
  "NetworkOptions": "Network Options ",
  "AutoDetectProxy": "Auto detect proxy",
  "ProxyAddress": "Proxy Address",
  "SocksProxy": "SOCKS Proxy",
  "Socksv4": "SOCKS v4",
  "Socksv5": "SOCKS v5",
  "ProxyDomain": "Domain(if any)",
  "Username": "Username",
  "Password": "Password",
  "ByPassProxy": "Bypass proxy settings",
  "ConnectionTimeoutHelp": "The time allowed for each screen sharing connection attempt",
  "RetriesHelp": "The number of times screen sharing will attempt to connect",
  "AutoDetectProxyHelp": "Screen sharing will automatically detect proxy settings",
  "SocksProxyHelp": "Use your browser's SOCKS proxy to connect",
  "ByPassProxyHelp": "Don't use proxy information to connect",
  "Advanced": "(Advanced)",
  "OSNotSupported": "Operating system not supported.",
  "RestrictAccess": "Java plug-in must be allowed in your  web browser. Restart the browser and allow java when prompted.",
  "CheckInternetConn": "Check internet connection",
  "AppletLoadTimeout": "Screen sharing didn't load. Check your connection and try again.",
  "UpdateClientFailed": "An internal screen sharing error occurred. Please try again.",
  "UnableToUpdateClient": "An internal screen sharing error occurred. Please try again.",
  "FileDamaged": "File damaged ",
  "DownloadFailed": "Download failed ",
  "UnableToLaunch": "An internal screen sharing error occurred.",
  "InstallationFailed": "Installation plug-in failed. ",
  "LoadConfigFailed": "Screen sharing is undergoing maintenance. Please try again later.",
  "ViewerStarted": "You're viewing {%1%}'s screen.",
  "ViewerStopped": "You're no longer viewing {%1%}'s screen.",
  "SharingStarted": "{%1%} started screen sharing.",
  "SharingStopped": "{%1%} stopped screen sharing.",
  "SendUsYourFeedback": "Send us your feedback",
  "JavaPluginDisabled": "Java plug-in must be installed and enabled in your Web browser.",
  "JavaSettingsError": "Java must be enabled in your operating system.",
  "Howto": "How to...",
  "FavoritesLimit": "Limit: {%1%} favorites",
  "MaxFavChars": "Limit: {%1%} characters",
  "FavNotSaved": "Couldn't save changes, try again.",
  "DuplicateFavName": "Name already exists, try again.",
  "AllUsersAreOffline": "Everyone is offline",
  "History": "Recent history",
  "ViewHistory": "View chat history",
  "LoadingHistory": "Loading history, please wait...",
  "NoChatsFound": " You don't have any recent chats.",
  "BackToHistory": "Back to chat history",
  "HistoryFailed": "Error getting chat history, {%1%}please try again.",
  "LoadingHistoryMsgs": "Loading history",
  "Searching": "Searching",
  "oneWeek": "Week",
  "oneMonth": "Month",
  "allTime": "All",
  "historyMessage": "View earlier messages",
  "MeetupsIntro": "New to Meetups ?",
  "MeetupsDownloadTxt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean porta sagittis lectus, eu tincidunt eros mollis eget. Suspendisse tempus, lacus tempor tristique volutpat, tortor urna sollicitudin lacus, sit amet blandit sapien est id est.",
  "MeetupsSDSDown": "Oops! Something went wrong... Please download again.",
  "MeetupsButtonTxt": "Get it now !"
};