/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
var originalSenderAddressElem=document.getElementById(ChatterEmailSettingsConstants.ORIGINAL_SENDER_ADDRESS_ID),senderAddressElem=document.getElementById(ChatterEmailSettingsConstants.SENDER_ADDRESS_ID),collaborationEmailElem=document.getElementById(ChatterEmailSettingsConstants.COLLABORATION_EMAIL_ID),emailReplyToChatterPrefElem=document.getElementById(ChatterEmailSettingsConstants.EMAIL_REPLY_TO_CHATTER_ID),emailToChatterPrefElem=document.getElementById(ChatterEmailSettingsConstants.EMAIL_TO_CHATTER_ID),
chatterEmailAttachmentPrefElem=document.getElementById(ChatterEmailSettingsConstants.CHATTER_EMAIL_ATTACHMENT_ID);function ChatterEmailSettings(){}ChatterEmailSettings.prototype.verificationConfirmation=function(){return originalSenderAddressElem.value!==senderAddressElem.value&&""!==senderAddressElem.value.trim()&&isValidEmail(senderAddressElem.value)?confirm(LC.getLabel("Page_ChatterEmailSettings","confirmationMessage",senderAddressElem.value)):!0};
ChatterEmailSettings.prototype.emailPrefChanged=function(a){a.checked||(null!==emailReplyToChatterPrefElem&&(emailReplyToChatterPrefElem.checked=!1),null!==emailToChatterPrefElem&&(emailToChatterPrefElem.checked=!1),null!==chatterEmailAttachmentPrefElem&&(chatterEmailAttachmentPrefElem.checked=!1))};ChatterEmailSettings.prototype.emailToChatterPrefChanged=function(a){!a.checked&&null!==chatterEmailAttachmentPrefElem&&(chatterEmailAttachmentPrefElem.checked=!1)};
ChatterEmailSettings.prototype.enableEmailPrefOnDependentChange=function(a){a.checked&&(collaborationEmailElem.checked=!0)};ChatterEmailSettings.prototype.enableEmailToChatterPrefOnDependentChange=function(a){a.checked&&(emailToChatterPrefElem.checked=!0,collaborationEmailElem.checked=!0)};
function ClobFieldShrinkageScanner(a){Sfdc.apply(this,a||{});this.lengthElement=Sfdc.get(this.lengthId);this.pauseClick=!1;a=LC.getLabel("Page_CustFieldEdit","ScanLabel");var b=this.isMaxLengthScannable?LC.getLabel("Page_CustFieldEdit","warning_scan_clob_shrinkage"):LC.getLabel("Page_CustFieldEdit","warning_no_scan_clob_shrinkage");this.scanDialogConfig={title:LC.getLabel("Page_CustFieldEdit","ScanDialogTitle"),msg:b,buttons:this.isMaxLengthScannable?{yes:a,no:LC.getLabel("Buttons","cancel")}:Ext.Msg.OK,
icon:this.isMaxLengthScannable?Ext.Msg.INFO:Ext.Msg.WARNING,fn:this.handleButtonClick,scope:this};ClobFieldShrinkageScanner.INSTANCE=this;Sfdc.on(document.getElementById(this.formId),"click",function(a){ClobFieldShrinkageScanner.INSTANCE.pauseClick&&Sfdc.Event.preventDefault(a)})}
ClobFieldShrinkageScanner.prototype.handleButtonClick=function(a){"yes"==a&&(a={},a[AjaxScanFieldsForShrinkage.pFIELD_ID]=this.fieldId,a[AjaxScanFieldsForShrinkage.pENTITY_NAME]=this.entityEnumOrId,a[AjaxScanFieldsForShrinkage.pLENGTH_SPECIFIED]=this.lengthElement.value,Sfdc.Ajax.request(this.scanServletUrl,{success:this.handleScanResponse,context:this,data:a,method:"POST",failure:function(){this.pauseClick=!1}}))};
ClobFieldShrinkageScanner.prototype.handleElementOnChange=function(a,b){this.pauseClick=!0;try{var c={};c[AjaxInNumericRange.pLOW]=this.minimumClobLength;c[AjaxInNumericRange.pTO_TEST]=b;c[AjaxInNumericRange.pHIGH]=a;Sfdc.Ajax.request(this.compareServletUrl,{success:this.handleCompareResponse,context:this,data:c,method:"POST",failure:function(){this.pauseClick=!1}})}catch(d){this.pauseClick=!1}};
ClobFieldShrinkageScanner.prototype.handleCompareResponse=function(a){try{!0===Util.evalAjaxServletOutput(a)[AjaxInNumericRange.pRESULT]&&Ext.Msg.show(this.scanDialogConfig)}finally{this.pauseClick=!1}};ClobFieldShrinkageScanner.prototype.handleScanResponse=function(a){var b=Util.evalAjaxServletOutput(a);a=b.scanResultMsg;b=Ext.Msg[b.scanResultWarnLevel];Ext.Msg.show({title:LC.getLabel("Page_CustFieldEdit","ScanResultsDialogTitle"),msg:a,buttons:Ext.Msg.OK,icon:b})};
function CustomFieldDefinitionPage(){}
CustomFieldDefinitionPage.warnAboutPotentialDataLoss=function(b,a){top.ffInAlert||(top.ffInAlert=!0,a.originalValue=a.defaultValue,a.originalChecked=a.defaultChecked,a.warnAboutPotentialDataLoss||(a.warnAboutPotentialDataLoss=Dialogs.createWarningDialog(LC.getLabel("Page_CustFieldEdit","potentialDataLossHeader"),LC.getLabel("Page_CustFieldEdit","potentialDataLossText"),"",LC.getLabel("Buttons","confirm"),LC.getLabel("Buttons","cancel"),function(){CustomFieldDefinitionPage.warningConfirm(a)},function(){CustomFieldDefinitionPage.warningCancel(a);
return!1}),a.warnAboutPotentialDataLoss.displayX=!1),a.warnAboutPotentialDataLoss.show())};
CustomFieldDefinitionPage.warnAboutIntegrationImpact=function(b,a){top.ffInAlert||(top.ffInAlert=!0,a.originalValue=a.defaultValue,a.originalChecked=a.defaultChecked,a.warnAboutIntegrationImpact||(a.warnAboutIntegrationImpact=Dialogs.createWarningDialog(LC.getLabel("Page_CustFieldEdit","potentialIntegrationImpactHeader"),LC.getLabel("Page_CustFieldEdit","potentialIntegrationImpactText"),"",LC.getLabel("Buttons","confirm"),LC.getLabel("Buttons","cancel"),function(){CustomFieldDefinitionPage.warningConfirm(a)},
function(){CustomFieldDefinitionPage.warningCancel(a)}),a.warnAboutIntegrationImpact.displayX=!1),a.warnAboutIntegrationImpact.show())};CustomFieldDefinitionPage.warningConfirm=function(b){top.ffInAlert=!1};CustomFieldDefinitionPage.warningCancel=function(b){b.value=b.originalValue;b.checked=b.originalChecked;top.ffInAlert=!1};
var EmailRoutingAddress={toggleTaskStatus:function(b,c){var d=document.getElementById(b),a=document.getElementById(c);d.checked?(a.options[a.selectedIndex].text=EmailRoutingAddress.taskStatusPrevValue,a.disabled=!1):(EmailRoutingAddress.taskStatusPrevValue=a.options[a.selectedIndex].text,a.options[a.selectedIndex].text=" ",a.disabled=!0)}};
function EmailRelay(){}EmailRelay.prototype.checkActivateRestrictToDomains=function(){var a=document.getElementById(EmailRelayConstants.ACTIVATE_RESTRICT_TO_DOMAINS_ID),b=document.getElementById(EmailRelayConstants.RESTRICT_TO_DOMAINS_ID),c=document.getElementById(EmailRelayConstants.RESTRICT_TO_DOMAINS_HIDDEN_ID);a.checked?b.disabled=!1:(b.value="",c.value="",b.disabled=!0)};
EmailRelay.prototype.changeRestrictToDomains=function(){var a=document.getElementById(EmailRelayConstants.RESTRICT_TO_DOMAINS_ID);document.getElementById(EmailRelayConstants.RESTRICT_TO_DOMAINS_HIDDEN_ID).value=a.value};
EmailRelay.prototype.handleTlsChange=function(){var a=document.getElementById(EmailRelayConstants.EMAIL_RELAY_TLS_SETTING_ID),b=document.getElementById(EmailRelayConstants.EMAIL_HOST_PORT_ID),a=a.options[a.selectedIndex].value,c=b.selectedIndex;0==a&&1==c?b.options[0].selected=!0:0!=a&&0==c&&(b.options[1].selected=!0)};
function EmailToSalesforceDeactivationDialog(c,a,b,e){this.id=c;this.isModal=!0;this.formId="emailDeactivation";this.windowName="";this.width=480;this.btnId=b;this.sendEmailNotificationId=a;this.isEmailConfigEnabled=e;this.addEvents()}EmailToSalesforceDeactivationDialog.HEIGHT=80;EmailToSalesforceDeactivationDialog.prototype=new OverlayDialog;
EmailToSalesforceDeactivationDialog.prototype.showDeActivationNotification=function(){this.setTitle(LC.getLabel("GoogleAppsActivationUi","deactivateTitle"));this.createContent();this.show();this.focusInOverlay()};
EmailToSalesforceDeactivationDialog.prototype.createContent=function(){var c=document.getElementById(this.getContentId()),a=[];a.push("\x3cdiv\x3e");a.push("\x3ctable \x3e");a.push("\x3ctr\x3e\x3ctd\x3e");a.push('\x3cimg src\x3d"'+UserContext.getUrl("/s.gif")+'" alt\x3d"Warning"  class\x3d"warningLarge" style\x3d"margin-right: 15px" title\x3d"Warning"/\x3e');a.push("\x3c/td\x3e\x3ctd\x3e");a.push('\x3cspan  class\x3d"deactivateWarningHeader"\x3e');a.push(LC.getLabel("GoogleDocsActivationUi","deactivateWarningHeader"));
a.push("\x3c/span\x3e");a.push('\x3cul class\x3d"deactivateWarningUl"\x3e');a.push("\x3cli\x3e"+LC.getLabel("Page_EmailToSalesforceOrgSetup","whatDeactivatingWillDo1")+"\x3c/li\x3e");a.push("\x3cli\x3e"+LC.getLabel("Page_EmailToSalesforceOrgSetup","whatDeactivatingWillDo2")+"\x3c/li\x3e");this.isEmailConfigEnabled&&a.push("\x3cli\x3e"+LC.getLabel("Page_EmailToSalesforceOrgSetup","whatDeactivatingWillDo3")+"\x3c/li\x3e");a.push("\x3c/ul\x3e\n\x3c/td\x3e\x3c/tr\x3e\n");a.push("\x3c/table\x3e\x3c/div\x3e");
a.push("\x3cdiv class\x3d'buttons'\x3e");var b=LC.getLabel("GoogleAppsActivationUi","deactivateButton");a.push('\x3cinput class\x3d"btn" type\x3d"button" id\x3d"overlayDeactivateButton" value\x3d"');a.push(b);a.push('" title\x3d"');a.push(b);a.push('" onclick\x3d"');a.push("if(EmailToSalesforceNotificationEmailDialog.prototype.savePage('dontsend','");a.push(this.sendEmailNotificationId);a.push("','");a.push(this.btnId);a.push("')) { sfdcPage.getDialogById('");a.push(this.id);a.push("').hide(); }");
a.push('"\x3e');b=LC.getLabel("Buttons","cancel");a.push('\x3cinput class\x3d"btn" type\x3d"button" value\x3d"');a.push(b);a.push('" title\x3d"');a.push(b);a.push('" onclick\x3d"');a.push("sfdcPage.getDialogById('");a.push(this.id);a.push("').cancel(); document.getElementById('");a.push(this.btnId);a.push("').focus();\"\x3e");a.push("\x3c/div\x3e");c.innerHTML=a.join("")};EmailToSalesforceDeactivationDialog.prototype.focusInOverlay=function(){document.getElementById("overlayDeactivateButton").focus()};
EmailToSalesforceDeactivationDialog.getDialog=function(c,a,b,e){var d=sfdcPage.getDialogById(c);if(d)return d;d=new EmailToSalesforceDeactivationDialog(c,a,b,e);d.register();return d};
function EmailToSalesforceNotificationEmailDialog(c,a,b,d,f,g,h){this.id=c;this.userSetupUrl=a;this.adminUserName=b;this.isModal=!0;this.formId="emailNotificationInputForm";this.errorElementId="errorMsg";this.windowName="";this.width=675;this.emailSubjectId=d;this.emailBodyId=f;this.sendEmailNotificationId=g;this.btnId=h;this.addEvents()}EmailToSalesforceNotificationEmailDialog.HEIGHT=80;EmailToSalesforceNotificationEmailDialog.prototype=new OverlayDialog;
EmailToSalesforceNotificationEmailDialog.prototype.showEmailNotification=function(){this.setTitle(LC.getLabel("Page_EmailToUsers","page_title"));this.createContent();this.show();this.focusInOverlay()};
EmailToSalesforceNotificationEmailDialog.prototype.createContent=function(){var c=document.getElementById(this.getContentId()),a=[];a.push("\x3ctable\x3e");a.push('\x3ctr\x3e\x3ctd align\x3d"right"\x3e');a.push("\x3cB\x3e"+LC.getLabel("Page_EmailToUsers","to")+"\x3c/B\x3e");a.push("\x3c/td\x3e\x3ctd\x3e");a.push(LC.getLabel("Page_EmailToUsers","allActiveUsers"));a.push("\x3c/td\x3e\x3c/tr\x3e");a.push('\x3ctr\x3e\x3ctd align\x3d"right"\x3e');a.push("\x3cB\x3e"+LC.getLabel("Page_EmailToUsers","emailSubjectLabel")+
"\x3c/B\x3e");a.push("\x3c/td\x3e\x3ctd\x3e");a.push('\x3cinput id\x3d"subject" type\x3d"text" size\x3d"75" name\x3d"subject" title\x3d"');a.push(LC.getLabel("Page_EmailToUsers","emailSubjectTitle"));a.push('" value\x3d"'+LC.getLabel("Page_EmailToUsers","emailSubject")+'"/\x3e');a.push("\x3c/td\x3e\x3c/tr\x3e");a.push("\x3ctr\x3e\x3ctd\x3e");a.push("\x3cB\x3e"+LC.getLabel("Page_EmailToUsers","emailBodyLabel")+"\x3c/B\x3e");a.push("\x3c/td\x3e\x3ctd\x3e\x26nbsp;\x3c/td\x3e\x3c/tr\x3e");a.push("\x3c/table\x3e");
a.push('\x3ctextarea id\x3d"body" name\x3d"body" rows\x3d"10" cols\x3d"100" title\x3d"'+LC.getLabel("Page_EmailToUsers","emailBodyTitle")+'"\x3e');a.push(LC.getLabel("Page_EmailToUsers","emailBody",this.userSetupUrl,this.adminUserName));a.push("\x3c/textarea\x3e");a.push("\x3cdiv class\x3d'buttons'\x3e");var b=LC.getLabel("Page_EmailToUsers","sendNotificationEmail");a.push("\x3cinput class\x3d'btn' type\x3d'button' value\x3d'");a.push(b);a.push("' title\x3d'");a.push(b);a.push("' onclick\x3d\"");
a.push("if(sfdcPage.getDialogById('");a.push(this.id);a.push("').sendEmail()) { sfdcPage.getDialogById('");a.push(this.id);a.push("').hide(); }\"\x3e");0<=this.btnId.indexOf("saveBtn")?(b=LC.getLabel("Page_EmailToUsers","skipThisStep"),a.push("\x3cinput class\x3d'btn' type\x3d'button' value\x3d'"),a.push(b),a.push("' title\x3d'"),a.push(b),a.push("' onclick\x3d\""),a.push("if(sfdcPage.getDialogById('"),a.push(this.id),a.push("').savePage('dontsend','"),a.push(this.sendEmailNotificationId),a.push("','"),
a.push(this.btnId),a.push("')) { sfdcPage.getDialogById('"),a.push(this.id),a.push("').hide(); }\"\x3e")):(b=LC.getLabel("Buttons","cancel"),a.push("\x3cinput class\x3d'btn' type\x3d'button' value\x3d'"),a.push(b),a.push("' title\x3d'"),a.push(b),a.push("' onclick\x3d\""),a.push("sfdcPage.getDialogById('"),a.push(this.id),a.push("').cancel(); document.getElementById('"),a.push(this.btnId),a.push("').focus();\"\x3e"));a.push("\x3c/div\x3e");c.innerHTML=a.join("")};
EmailToSalesforceNotificationEmailDialog.prototype.focusInOverlay=function(){document.getElementById("body").focus()};EmailToSalesforceNotificationEmailDialog.prototype.sendEmail=function(){var c=document.getElementById("subject"),a=document.getElementById("body"),b=document.getElementById(this.emailSubjectId),d=document.getElementById(this.emailBodyId);b.value=c.value;d.value=a.value;return this.savePage("send",this.sendEmailNotificationId,this.btnId)};
EmailToSalesforceNotificationEmailDialog.prototype.savePage=function(c,a,b){document.getElementById(a).value=c;document.getElementById(b).click();return!0};EmailToSalesforceNotificationEmailDialog.getDialog=function(c,a,b,d,f,g,h){var e=sfdcPage.getDialogById(c);if(e)return e;e=new EmailToSalesforceNotificationEmailDialog(c,a,b,d,f,g,h);e.register();return e};
function EmailAttachmentManagement(){}
EmailAttachmentManagement.prototype.toggleSelectOption=function(f){var a=document.getElementById(EmailAttachmentManagementConstants.FILE_NAME_ID),b=document.getElementById(EmailAttachmentManagementConstants.SENDER_LOOKUP_ID),c=document.getElementById(EmailAttachmentManagementConstants.START_DATE_ID),d=document.getElementById(EmailAttachmentManagementConstants.END_DATE_ID),e=document.getElementById(EmailAttachmentManagementConstants.LOOKUP_URL_ID);f==EmailAttachmentManagementConstants.SEARCH_BY_DATA?(a.disabled=
!1,b.disabled=!1,c.disabled=!1,d.disabled=!1,e.disabled=!0):(a.disabled=!0,b.disabled=!0,c.disabled=!0,d.disabled=!0,e.disabled=!1)};
function EmailAddrEdit(){}EmailAddrEdit.prototype.changeToCancelRetURL=function(){var a=new QueryString("");a.add(EmailAddrEditConstants.pSAVE_CANCEL,"true");document.editPage.elements.retURL.value=UrlMap.getURL("EmailAuthorPopupCloser")+a.toString()};
function EmailCCBccLookup(){}EmailCCBccLookup.prototype.storeAddrs=function(a,b,c,g){b.value="";c.value="";if(Sfdc.isDefAndNotNull(a))for(var f=!0,d=0,e;d<a.length;d++)if((e=a.options[d])&&""!==e.value&&e.value!==g)f?f=!1:(b.value+=EmailAuthorConstants.EMAIL_ADDR_DELIM,c.value+=EmailAuthorConstants.EMAIL_ADDR_DELIM),b.value+=a.options[d].text,c.value+=a.options[d].value};
EmailCCBccLookup.prototype.storeAllAddresses=function(a){EmailCCBccLookup.prototype.storeAddrs(document.getElementById(EmailCCBccLookupConstants.ADDITIONAL_TO_ID),document.getElementById(EmailCCBccLookupConstants.ADDITIONAL_TO_NAME_ID),document.getElementById(EmailCCBccLookupConstants.ADDITIONAL_TO_ADDR_ID),a);EmailCCBccLookup.prototype.storeAddrs(document.getElementById(EmailCCBccLookupConstants.CC_ID),document.getElementById(EmailCCBccLookupConstants.CC_NAME_ID),document.getElementById(EmailCCBccLookupConstants.CC_ADDR_ID),
a);EmailCCBccLookup.prototype.storeAddrs(document.getElementById(EmailCCBccLookupConstants.BCC_ID),document.getElementById(EmailCCBccLookupConstants.BCC_NAME_ID),document.getElementById(EmailCCBccLookupConstants.BCC_ADDR_ID),a)};EmailCCBccLookup.prototype.changeContactType=function(a){EmailCCBccLookup.prototype.storeAllAddresses(a);document.forms[EditPageConstants.pEDIT_PAGE].submit();return!0};
EmailCCBccLookup.prototype.sizeToContent=function(){for(var a,b,c=0;5>c;c++){if(document.height)a=document.height;else if(document.body.offsetHeight)a=document.body.offsetHeight;else break;b=window.innerHeight?window.innerHeight:document.documentElement.clientHeight&&0<document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.clientHeight;if(a>b&&window.resizeBy)window.resizeBy(0,a-b);else break}};
var backgroundIFrameTitle;function EmailTemplateEditorUi(a,b,c){registerEmptyCellText(LC.getLabel("EmailTemplate","emptyCellText"));this.editAreaIds=null;backgroundIFrameTitle=a;this.isCustom=b;this.formName=c}EmailTemplateEditorUi.prototype.gatherEditableIds=function(){for(var a={},b=document.getElementsByTagName("td"),c=0,e=0,d;e<b.length;e++)d=b[e],null!==d.id&&0<d.id.length&&(a[c]=d.id,c++);this.editAreaIds=[];for(b=0;b<c;b++)this.editAreaIds[b]=a[b]};
EmailTemplateEditorUi.prototype.getTopTable=function(){var a=document.getElementById("topTable"),b=document.getElementsByTagName("table");!a&&b&&(a=b[0]);return a};EmailTemplateEditorUi.prototype.getDefaultPopupWidth=function(){var a=getTopTable();return a?Math.min(Math.max(a.offsetWidth+60,500),1024):500};EmailTemplateEditorUi.prototype.getDefaultPopupHeight=function(){var a=getTopTable();return a?Math.min(Math.max(a.offsetHeight+200,500),768):500};
EmailTemplateEditorUi.prototype.init=function(){top!=this?this.isCustom?document.body&&(parent.setFrameWidth(document.body.scrollWidth),parent.setFrameHeight(document.body.scrollHeight)):(this.gatherEditableIds(),setEditableIds(this.editAreaIds),registerLockingConfirmText(LC.getLabel("EmailTemplate","SetLockedConfirmText")),setLockedImageSrc(UserContext.getUrl("/email/wysiwyg/images/locked.gif")),setUnlockedImageSrc(UserContext.getUrl("/email/wysiwyg/images/unlocked.gif")),registerEditForm(parent.document.forms[this.formName]),
initializeEditor(),top.editFinishedLoading=!0):window.resizeTo(this.getDefaultPopupWidth(),this.getDefaultPopupHeight())};
function EmailTemplatePreview(){}
EmailTemplatePreview.prototype.toggleRctOptions=function(a,b){var h=document.getElementById(a+"Option0"),c=document.getElementById(a+"Id"),d=document.getElementById(b),e=document.getElementById(b+LookupInputElement.pLOOKUP_WIDGET),f=document.getElementById(a+EmailTemplatePreviewConstants.LOOKUP_REQUIRED_BLOCK_ID),g=document.getElementById(a+EmailTemplatePreviewConstants.ID_REQUIRED_BLOCK_ID);h.checked?(c.disabled=!0,g.className="",d.disabled=!1,e.disabled=!1,f.className=EmailTemplatePreviewConstants.REQUIRED_BLOCK_CLASS):
(c.disabled=!1,g.className=EmailTemplatePreviewConstants.REQUIRED_BLOCK_CLASS,d.disabled=!0,e.disabled=!0,f.className="")};
var CampaignInfluenceSetupUi={setAutomaticAssociation:function(b){for(var a=1,c=document.getElementById("fcol"+a),d=document.getElementById("fop"+a),e=document.getElementById("fval"+a);c;)c.disabled=!b,d.disabled=!b,e.disabled=!b,a++,c=document.getElementById("fcol"+a),d=document.getElementById("fop"+a),e=document.getElementById("fval"+a);if(a=document.getElementById("bool_filter"))a.disabled=!b;if(a=document.getElementById("citf"))a.disabled=!b}};
(function(){var d={canSeeSetup:!1,beginPeriodSelectController:null,periodsDisplayedController:null,periodSelectController:null,periodLabels:null,MONTHLY:0,QUARTERLY:1,peirodType:null,defaultPeriodType:null,beginningId:ForecastingPage.BEGIN_PERIOD_CONTROL_NAME,displayingId:ForecastingPage.PERIODS_DISPLAYED_CONTROL_NAME,MONTHLY_MAX:12,QUARTERLY_MAX:8,MONTHLY_DEFAULT:6,QUARTERLY_DEFAULT:4,beginningPeriod:0,displayingPeriod:1,canSeeQuantity:!0,dataSourceController:null,revenueController:null,quantityController:null,
dialog:null,form:null,ORG_DATE_RANGE:1,initialized:!1,fctEnabled:!1,productFamilyPrefPresent:!1,validateFieldSelector:function(){var a,b;"splits"==this.dataSourceController.value?(a=Sfdc.get("colselector_opportunitysplitrevenue_selectedFieldsElementId").value,b=Sfdc.get("editPage_colselector_opportunitysplitrevenue_errorMsg")):"overlay"==this.dataSourceController.value?(a=Sfdc.get("colselector_opportunityoverlayrevenue_selectedFieldsElementId").value,b=Sfdc.get("editPage_colselector_opportunityoverlayrevenue_errorMsg")):
"productFamily"==this.dataSourceController.value?(a=Sfdc.get("colselector_opportunitylineitemrevenue_selectedFieldsElementId").value,b=Sfdc.get("editPage_colselector_opportunitylineitemrevenue_errorMsg")):(a=Sfdc.get("colselector_default_selectedFieldsElementId").value,b=Sfdc.get("editPage_colselector_default_errorMsg"));if(15<Sfdc.get(a).options.length)return a=LC.getLabel("Forecasting_SetupPage","filter_select_error","15"),Sfdc.Dom.setText(b,a),Sfdc.Dom.show(b),!1;Sfdc.Dom.setText(b,"");Sfdc.Dom.hideByDisplay(b)},
updateQuantitySelectors:function(){!0===this.revenueController.checked&&!1===this.quantityController.checked?(Sfdc.Dom.set(this.revenueController,"disabled",""),Sfdc.Dom.set(this.revenueController,"checked","true")):!1===this.revenueController.checked&&!0===this.quantityController.checked&&(Sfdc.Dom.set(this.quantityController,"disabled",""),Sfdc.Dom.set(this.quantityController,"checked","true"));!0===this.dataSourceController.disabled&&(this.dataSourceController.disabled=!1)},showConfirmationDialog:function(a){var b=
!1;this.dialog||(b=Sfdc.get("confirmationContent"),this.dialog=OverlayDialogElement.getDialog("confirmationDialog"),this.dialog.isModal=!0,this.dialog.setWidth(480),this.dialog.setTitle(LC.getLabel("Forecasting_SetupPage","confirm_change")),this.dialog.contents=b.innerHTML,this.dialog.createContent(),Sfdc.Dom.removeChild(b),b=!0);var c=Sfdc.Dom.getFirstChild(Sfdc.get("confirmationDialog_buttons"));Sfdc.Dom.set(c,"disabled","true");Sfdc.Dom.set(Sfdc.get("confirmChk"),"checked","");Sfdc.Dom.updateHTML(Sfdc.get("confirmMessage"),
a);this.dialog.show();b&&(a=Sfdc.get("confirmChk"),Sfdc.on(a,"click",function(){this.checked?Sfdc.Dom.set(c,"disabled",""):Sfdc.Dom.set(c,"disabled","true")}),Sfdc.on(c,"click",function(){this.form.submit()},this))},checkForConfirmation:function(){var a,b=!1;a=Sfdc.get("confirmMessage").getAttribute("helpUrl");!1===this.fctEnabled?(a=LC.getLabel("Forecasting_SetupPage","confirm_disable",a),b=!0):(a=LC.getLabel("Forecasting_SetupPage","confirm_disable",a),!this.form.adjustmentEnable.checked&&"on"===
this.form.adjustmentOrigState.value?b=!0:this.isDataSourceChanged()?b=!0:this.periodType!=this.defaultPeriodType&&(b=!0));b?this.showConfirmationDialog(a):this.form.submit()},isDataSourceChanged:function(){var a=!1;this.defaultQuantityEnabled&&!this.quantityEnabled?a=!0:this.defaultRevenueEnabled&&!this.revenueEnabled?a=!0:this.productFamilyPrefPresent&&this.defaultProductFamilyEnabled!=this.productFamilyEnabled?a=!0:this.defaultDataSource!=this.dataSourceController.value&&(a=!0);return a},submitForm:function(){"true"===
this.form.isForecasting3Enabled.value?this.checkForConfirmation():this.form.submit()},executeDuelingSelectorAndSubmitForm:function(){var a,b;b="splits"==this.dataSourceController.value?"colselector_opportunitysplitrevenue_duelingSaveSelectScript":"overlay"==this.dataSourceController.value?"colselector_opportunityoverlayrevenue_duelingSaveSelectScript":"productFamily"==this.dataSourceController.value?"colselector_opportunitylineitemrevenue_duelingSaveSelectScript":"colselector_default_duelingSaveSelectScript";
a=Sfdc.get(b);var c=a.getAttribute("script"),c="\x3cscript\x3e"+c.substring(0,c.indexOf(";")+1)+"\x3c/script\x3e",e=this;Sfdc.userAgent.isIE?Ext.get(b).update(c,!0,function(){e.submitForm()}):Sfdc.Dom.updateHTML(a,c,!0,function(){e.submitForm()})},submit:function(){this.form=Sfdc.get("editPage");try{if(this.fctEnabled){this.updateQuantitySelectors();if(!1===this.validateFieldSelector())return!1;this.executeDuelingSelectorAndSubmitForm()}else this.submitForm()}catch(a){return Sfdc.sendGack("FORECASTING_SETUP",
a),!1}},updateDataSources:function(){this.revenueEnabled=this.revenueController.checked;this.quantityEnabled=this.quantityController.checked;this.productFamilyPrefPresent&&(this.productFamilyEnabled="productFamily"==this.dataSourceController.value);"splits"==this.dataSourceController.value||"overlay"==this.dataSourceController.value?(Sfdc.Dom.set(this.quantityController,"checked",""),Sfdc.Dom.set(this.quantityController,"disabled","true"),Sfdc.Dom.set(this.revenueController,"checked","true"),Sfdc.Dom.set(this.revenueController,
"disabled","true")):(Sfdc.Dom.set(this.quantityController,"disabled",""),Sfdc.Dom.set(this.revenueController,"disabled",""),!0===this.revenueEnabled&&!1===this.quantityEnabled?Sfdc.Dom.set(this.revenueController,"disabled","true"):!1===this.revenueEnabled&&!0===this.quantityEnabled&&Sfdc.Dom.set(this.quantityController,"disabled","true"));this.updateColumnFilter()},updateColumnFilter:function(){var a=Sfdc.get("filterType_colselector_default"),b=Sfdc.get("filterType_colselector_opportunitysplitrevenue"),
c=Sfdc.get("filterType_colselector_opportunityoverlayrevenue"),e=Sfdc.get("filterType_colselector_opportunitylineitemrevenue");"splits"==this.dataSourceController.value?(Sfdc.Dom.hideByDisplay(a),Sfdc.Dom.hideByDisplay(e),Sfdc.Dom.hideByDisplay(c),Sfdc.Dom.show(b)):"overlay"==this.dataSourceController.value?(Sfdc.Dom.hideByDisplay(a),Sfdc.Dom.hideByDisplay(e),Sfdc.Dom.show(c),Sfdc.Dom.hideByDisplay(b)):"productFamily"==this.dataSourceController.value?(Sfdc.Dom.hideByDisplay(a),Sfdc.Dom.hideByDisplay(b),
Sfdc.Dom.hideByDisplay(c),Sfdc.Dom.show(e)):(Sfdc.Dom.hideByDisplay(b),Sfdc.Dom.hideByDisplay(e),Sfdc.Dom.hideByDisplay(c),Sfdc.Dom.show(a))},updatePeriodRange:function(){var a=parseInt(this.periodsDisplayedController.value,10);this.updatePeriodRangeText(a,this.beginPeriodSelectController.selectedIndex)},updatePeriodRangeText:function(a,b){var c=this.periodLabels[b],e=this.periodLabels[b+a-1],c=1===a?this.isMonthly()?LC.getLabel("Forecasting_SetupPage","will_show_month",c):LC.getLabel("Forecasting_SetupPage",
"will_show_quarter",c):this.isMonthly()?LC.getLabel("Forecasting_SetupPage","will_show_months",a,c,e):LC.getLabel("Forecasting_SetupPage","will_show_quarters",a,c,e);Sfdc.Dom.updateHTML(Sfdc.get("monthsRange"),c)},updateDuelSelectorStatus:function(){var a=Sfdc.get("colselector_default_selectedFieldsElementId").value,b=Sfdc.get("colselector_default_availableFieldsElementId").value,c=Sfdc.get("colselector_opportunitysplitrevenue_selectedFieldsElementId").value,e=Sfdc.get("colselector_opportunitysplitrevenue_availableFieldsElementId").value,
d=Sfdc.get("colselector_opportunityoverlayrevenue_selectedFieldsElementId").value,f=Sfdc.get("colselector_opportunityoverlayrevenue_availableFieldsElementId").value,g=Sfdc.get("colselector_opportunitylineitemrevenue_selectedFieldsElementId").value,h=Sfdc.get("colselector_opportunitylineitemrevenue_availableFieldsElementId").value;this.canSeeSetup||(Sfdc.get(a).disabled="disabled",Sfdc.get(b).disabled="disabled",Sfdc.get(c).disabled="disabled",Sfdc.get(e).disabled="disabled",Sfdc.get(d).disabled="disabled",
Sfdc.get(f).disabled="disabled",Sfdc.get(g).disabled="disabled",Sfdc.get(h).disabled="disabled")},initDataSources:function(){this.canSeeSetup&&(this.revenueController=Sfdc.get("enableRevenue"),this.quantityController=Sfdc.get("enableQuantity"),this.productFamilyPrefPresent&&(this.defaultProductFamilyEnabled=this.productFamilyEnabled="productFamily"==this.dataSourceController.value),this.dataSourceController=Sfdc.get("forecastingDataSource"),2>this.dataSourceController.length&&(this.dataSourceController.disabled=
!0),this.revenueEnabled=this.revenueController.checked,this.quantityEnabled=this.quantityController.checked,this.defaultRevenueEnabled=this.revenueEnabled,this.defaultQuantityEnabled=this.quantityEnabled,this.defaultDataSource=this.dataSourceController.value,this.addDataSourceListener(),this.updateDataSources())},initPeriods:function(){this.canSeeSetup&&(this.defaultPeriodType=this.periodType=parseInt(Sfdc.get("defaultPeriodType").value,10),this.beginningPeriod=parseInt(Sfdc.get("beginningPeriodIndex").value,
10),this.displayingPeriod=parseInt(Sfdc.get("periodDurationIndex").value,10),this.loadPeriodLabels(!0))},loadPeriodLabels:function(a){var b=this,c={periodType:this.periodType,dateRangeType:this.ORG_DATE_RANGE};c[CSRFConstants.CSRF_TOKEN]=Sfdc.get("_CONFIRMATIONTOKEN").value;Sfdc.Ajax.post("/_ui/sales/forecasting/ui/ForecastingDateRangeServlet",function(c){c=Util.evalAjaxServletOutput(c);if(c.periodLabels)b.periodLabels=c.periodLabels,b.canSeeSetup?(b.updatePeriodControllers(a),b.updatePeriodList(a),
b.updatePeriodRange()):b.updatePeriodRangeText(b.displayingPeriod,b.beginningPeriod+b.getPeriodMax()),Sfdc.Dom.hideByDisplay(Sfdc.get("periodErrorMsg"));else{var d=Sfdc.get("periodErrorMsg");Sfdc.Dom.updateHTML(d,c.exTitle+c.exDesc);Sfdc.Dom.show(d)}},{data:c})},updatePeriodControllers:function(a){this.beginPeriodSelectController=Sfdc.get("beginPeriod");this.periodsDisplayedController=Sfdc.get("periodsDisplayed");this.periodSelectController=Sfdc.get("periodSelect");this.initPeriodSelectDefaultValue();
if(a)Sfdc.on(this.periodSelectController,"change",this.togglePeriodSettings,this)},addDataSourceListener:function(){Sfdc.on(this.revenueController,"click",function(){this.updateDataSources()},this);Sfdc.on(this.quantityController,"click",function(){this.updateDataSources()},this);Sfdc.on(this.dataSourceController,"change",function(){this.updateDataSources()},this)},addPeriodControllersListener:function(){var a=this;Sfdc.on(this.beginPeriodSelectController,"change",function(){a.updatePeriodRange()});
Sfdc.on(this.periodsDisplayedController,"change",function(){a.updatePeriodRange()})},initCanSeeSetup:function(){this.canSeeSetup="true"===Sfdc.get("canSeeForecastSetup").value.toLowerCase()},updatePeriodList:function(a){this.updateBeginningSelect();this.updateDisplayingSelect();(Sfdc.userAgent.isIE||a)&&this.addPeriodControllersListener()},updateBeginningSelect:function(){for(var a=[],b=this.getPeriodMax(),c=-b;c<=b;c++)a.push('\x3coption value\x3d"',c,'"'),c===this.beginningPeriod&&a.push(' selected\x3d"selected" '),
a.push("\x3e"),a.push(this.generateBeginningPeriodText(c)),a.push("\x3c/option\x3e");this.updateDom(this.beginningId,a)},updateDisplayingSelect:function(){for(var a=[],b=this.getPeriodMax(),c=1;c<=b;c++)a.push('\x3coption value\x3d"',c,'"'),c===this.displayingPeriod&&a.push(' selected\x3d"selected" '),a.push("\x3e"),a.push(this.generateDisplayingText(c)),a.push("\x3c/option\x3e");this.updateDom(this.displayingId,a)},generateDisplayingText:function(a){return this.isMonthly()?1===a?LC.getLabel("Forecasting_SetupPage",
"month_string"):LC.getLabel("Forecasting_SetupPage","months_string",a):1===a?LC.getLabel("Forecasting_SetupPage","quarter_string"):LC.getLabel("Forecasting_SetupPage","quarters_string",a)},updateDom:function(a,b){if(Sfdc.userAgent.isIE){var c='\x3cselect id\x3d"'+a+'" name\x3d"'+a+'"\x3e'+b.join("")+"\x3c/select\x3e",d=Sfdc.Dom.getParent(Sfdc.get(a),"div");Sfdc.userAgent.isIE7?(Ext.get(a).removeAllListeners(),d.innerHTML=c):Sfdc.Dom.updateHTML(d,c);this.beginningId===a?this.beginPeriodSelectController=
Sfdc.get(a):this.periodsDisplayedController=Sfdc.get(a)}else Sfdc.Dom.updateHTML(Sfdc.get(a),b.join(""))},generateBeginningPeriodText:function(a){return 0>a?this.generatePastText(a):0<a?this.generateFutureText(a):this.isMonthly()?LC.getLabel("Forecasting_SetupPage","current_month"):LC.getLabel("Forecasting_SetupPage","current_quarter")},generatePastText:function(a,b){return this.isMonthly()?-1===a?LC.getLabel("Forecasting_SetupPage","ago_month"):LC.getLabel("Forecasting_SetupPage","ago_months",-a):
-1===a?LC.getLabel("Forecasting_SetupPage","ago_quarter"):LC.getLabel("Forecasting_SetupPage","ago_quarters",-a)},generateFutureText:function(a,b){return this.isMonthly()?1===a?LC.getLabel("Forecasting_SetupPage","future_month"):LC.getLabel("Forecasting_SetupPage","future_months",a):1===a?LC.getLabel("Forecasting_SetupPage","future_quarter"):LC.getLabel("Forecasting_SetupPage","future_quarters",a)},togglePeriodSettings:function(){this.periodType=parseInt(this.periodSelectController.value,10);this.beginningPeriod=
0;this.displayingPeriod=this.isMonthly()?this.MONTHLY_DEFAULT:this.QUARTERLY_DEFAULT;this.loadPeriodLabels()},getPeriodMax:function(){return this.isMonthly()?this.MONTHLY_MAX:this.QUARTERLY_MAX},isMonthly:function(){return this.periodType===this.MONTHLY},initPeriodSelectDefaultValue:function(){for(var a=this.periodSelectController.options,b=a.length,c=0;c<b;c++)parseInt(a[c].value,10)===this.periodType&&(a[c].selected=!0)},toggleFctPref:function(){this.updateFctEnabledStatus(Sfdc.get("enableForecasting3").checked);
this.fctEnabled?(this.initialized||this.init(),Sfdc.Dom.show(Sfdc.get("allSettings"))):Sfdc.Dom.hideByDisplay(Sfdc.get("allSettings"))},init:function(){this.updateDuelSelectorStatus();this.initPeriods();this.initDataSources();this.initialized=!0},updateFctEnabledStatus:function(a){this.fctEnabled=a},initListeners:function(){this.canSeeSetup&&(Sfdc.on(Sfdc.get("save"),"click",d.submit,d),Sfdc.on(Sfdc.get("enableForecasting3"),"click",d.toggleFctPref,d))},initProductFamilyPrefPresent:function(){this.productFamilyPrefPresent=
Sfdc.get("enableProductFamilyPref")}};Sfdc.onReady(function(){try{Sfdc.get("isForecasting3Enabled")&&(d.initCanSeeSetup(),d.initProductFamilyPrefPresent(),"true"===Sfdc.get("isForecasting3Enabled").value&&(d.updateFctEnabledStatus(!0),d.init()),d.initListeners())}catch(a){Sfdc.sendGack("FORECASTING_SETUP",a)}});Sfdc.on(window,"unload",function(){this.form=this.dialog=this.dataSourceController=this.quantityController=this.revenueController=null},d)})();
var BusinessHoursPage={set24x7Hours:function(d,a,b,c){a=document.getElementById(a);b=document.getElementById(b);d?(a.className="timeInputActive",a.value=c,a.disabled=!0,b.className="timeInputActive",b.value=c,b.disabled=!0):(a.disabled=!1,b.disabled=!1)}};
function EmailToCaseSettings(a,b,c,d){this.e2cElem=document.getElementById(a);this.ode2cElem=document.getElementById(b);this.overLimitElem=document.getElementById(c);this.unAuthElem=document.getElementById(d)}EmailToCaseSettings.prototype.toggleFailureSettings=function(){this.ode2cElem.checked?(this.overLimitElem.disabled=!1,this.unAuthElem.disabled=!1):(this.overLimitElem.disabled=!0,this.unAuthElem.disabled=!0)};
EmailToCaseSettings.prototype.toggleEmailToCase=function(){this.e2cElem.checked?this.ode2cElem.disabled=!1:(this.ode2cElem.checked=!1,this.ode2cElem.disabled=!0);this.toggleFailureSettings()};
EmailToCaseSettings.prototype.onOnDemandChange=function(){if(this.ode2cElem.checked)this.toggleFailureSettings();else{var a=["\x3cdiv\x3e",LC.getLabel("EmailToCase","OnDemandDeactivationText"),"\x3c/div\x3e"].join("");Ext.Msg.show({title:LC.getLabel("EmailToCase","OnDemandDeactivationHeader"),msg:a,buttons:Ext.Msg.YESNO,buttonTextYes:Ext.MessageBox.buttonText.yes=LC.getLabel("EmailToCase","OnDemandDeactivateButton"),buttonTextNo:Ext.MessageBox.buttonText.no=LC.getLabel("Buttons","cancel"),minWidth:450,
scope:this,icon:Ext.Msg.WARNING,fn:function(a){"no"==a?this.ode2cElem.checked=!0:this.toggleFailureSettings()}})}};
var ChangePassword=function(a,b,c,d,f,e,g,h,k){this.SPECIAL_CHAR="!#$%-_\x3d+\x3c\x3e";this.minLength=a;this.isAlphaNumericRequired=b;this.isSpecialCharacterRequired=c;this.isUpperLowerCaseNumericRequired=d;this.isUpperLowerCaseNumericSpecialCharacterRequired=f;this.passwordPolicy=e;this.answerCannotContainPassword=g;this.weakLabel=LC.getLabel("Page_Change_Password","password_strength_weak");this.acceptableLabel=LC.getLabel("Page_Change_Password","password_strength_acceptable");this.strongLabel=LC.getLabel("Page_Change_Password",
"password_strength_strong");this.strengthTips=LC.getLabel("Page_Change_Password","password_strength_tips");this.strengthSpecialCharTips=LC.getLabel("Page_Change_Password","password_strength_specialchar_tips",this.SPECIAL_CHAR);this.strengthUpperLowerSpecialCharTips=LC.getLabel("Page_Change_Password","password_strength_upperlower_specialchar_tips",this.SPECIAL_CHAR);this.strengthStrong=LC.getLabel("Page_Change_Password","password_strength_good");this.strengthSpecialCharStrong=LC.getLabel("Page_Change_Password",
"password_strength_specialchar_good",this.SPECIAL_CHAR);this.neutralAltText=LC.getLabel("Page_Change_Password","neutral_alt_text");this.weakAltText=LC.getLabel("Page_Change_Password","weak_alt_text");this.acceptableAltText=LC.getLabel("Page_Change_Password","acceptable_alt_text");this.strongAltText=LC.getLabel("Page_Change_Password","strong_alt_text");h&&(this.weakLabel=this.weakLabel.toLowerCase(),this.acceptableLabel=this.acceptableLabel.toLowerCase(),this.strongLabel=this.strongLabel.toLowerCase());
0===this.getElementsByClassNameWorkaroundForIE("div","errorMsg").length?this.errorPageLoad=!1:this.errorPageLoad=!0;!0!==k&&this.genericListener();this.addListeners()};
ChangePassword.prototype.addListeners=function(){var a=this;document.getElementById(ChangePasswordConstants.pOLD_PASSWORD_ELEM)&&(document.getElementById(ChangePasswordConstants.pOLD_PASSWORD_ELEM).onkeyup=function(){a.genericListener()});document.getElementById(ChangePasswordConstants.pNEW_PASSWORD_ELEM).onkeyup=function(){a.genericListener()};document.getElementById(ChangePasswordConstants.pNEW_PASSWORD_CONFIRMATION_ELEM).onkeyup=function(){a.genericListener()};document.getElementById(ChangePasswordConstants.pANSWER_ELEM)&&
(document.getElementById(ChangePasswordConstants.pANSWER_ELEM).onkeyup=function(){a.genericListener()})};ChangePassword.prototype.genericListener=function(){this.errorPageLoad?(this.updateLabel(ChangePasswordConstants.pNEW_PASSWORD_STRENGTH_INFO_ELEM,this.passwordPolicy,void 0),this.errorPageLoad=!1):(this.passwordStrengthChecker(),this.passwordVerify(),document.getElementById(ChangePasswordConstants.pANSWER_ELEM)&&this.answerVerify(),this.cleanUpErrorMessages())};
ChangePassword.prototype.passwordStrengthChecker=function(){this.newPasswordUntrimmed=document.getElementById(ChangePasswordConstants.pNEW_PASSWORD_ELEM).value;this.newPassword=this.newPasswordUntrimmed.replace(/^\s+|\s+$/g,"");this.checkBlankPassword()||this.orgSpecificChecks()};
ChangePassword.prototype.updateNewPasswordIconAndLabel=function(a,b,c,d,f){this.updateIcon(ChangePasswordConstants.pNEW_PASSWORD_ICON_ELEM,UserContext.getUrl(a),d);this.updateLabel(ChangePasswordConstants.pNEW_PASSWORD_STRENGTH_ELEM,b,c);this.updateLabel(ChangePasswordConstants.pNEW_PASSWORD_STRENGTH_INFO_ELEM,f,void 0);this.updatePromptVisibility(b)};
ChangePassword.prototype.updatePromptVisibility=function(a){var b=document.getElementById(ChangePasswordConstants.pNEW_PASSWORD_STRENGTH_PROMPT);b&&(0<a.length?this.setStyleText(b,"display:inline;"):this.setStyleText(b,"display:none;"))};ChangePassword.prototype.checkBlankPassword=function(){return 0===this.newPassword.length?(this.updateNewPasswordIconAndLabel("/img/passwordStrength/neutral.gif","","pscNoEntry",this.neutralAltText,this.passwordPolicy),!0):!1};
ChangePassword.prototype.orgSpecificChecks=function(){if(this.newPassword.length>=this.minLength){var a=this.strengthTips;if(this.isAlphaNumericRequired){if(!this.newPassword.match(/\d+/)&&(this.newPassword.match(/[a-z]/)||this.newPassword.match(/[A-Z]/))||this.newPassword.match(/\d+/)&&!this.newPassword.match(/[a-z]/)&&!this.newPassword.match(/[A-Z]/)||!this.newPassword.match(/\d+/)&&!this.newPassword.match(/[a-z]/)&&!this.newPassword.match(/[A-Z]/)){this.strength=this.weakLabel;this.updateNewPasswordIconAndLabel("/img/passwordStrength/weak.gif",
this.weakLabel,"pscWeak",this.weakAltText,this.passwordPolicy);return}}else if(this.isSpecialCharacterRequired){if(!this.newPassword.match(/\d+/)||!this.newPassword.match(/[A-z]+/)||!this.newPassword.match(/[!|#|\$|%|\-|_|=|\+|<|>]+/)){this.strength=this.weakLabel;this.updateNewPasswordIconAndLabel("/img/passwordStrength/weak.gif",this.weakLabel,"pscWeak",this.weakAltText,this.passwordPolicy);return}a=this.strengthSpecialCharTips}else if(this.isUpperLowerCaseNumericRequired){if(!this.newPassword.match(/[A-Z]+/)||
!this.newPassword.match(/[a-z]+/)||!this.newPassword.match(/\d+/)){this.strength=this.weakLabel;this.updateNewPasswordIconAndLabel("/img/passwordStrength/weak.gif",this.weakLabel,"pscWeak",this.weakAltText,this.passwordPolicy);return}}else if(this.isUpperLowerCaseNumericSpecialCharacterRequired){if(!this.newPassword.match(/[A-Z]+/)||!this.newPassword.match(/[a-z]+/)||!this.newPassword.match(/\d+/)||!this.newPassword.match(/[!|#|\$|%|\-|_|=|\+|<|>]+/)){this.strength=this.weakLabel;this.updateNewPasswordIconAndLabel("/img/passwordStrength/weak.gif",
this.weakLabel,"pscWeak",this.weakAltText,this.passwordPolicy);return}a=this.strengthUpperLowerSpecialCharTips}this.strength=this.acceptableLabel;this.updateNewPasswordIconAndLabel("/img/passwordStrength/acceptable.gif",this.acceptableLabel,"pscAcceptable",this.acceptableAltText,a);this.passwordStrengthExtraChecks()}else this.strength=this.weakLabel,this.updateNewPasswordIconAndLabel("/img/passwordStrength/weak.gif",this.weakLabel,"pscWeak",this.weakAltText,this.passwordPolicy)};
ChangePassword.prototype.passwordStrengthExtraChecks=function(){8<=this.newPassword.length&&(this.newPassword.match(/\d+/)&&this.newPassword.match(/[a-z]/)&&this.newPassword.match(/[A-Z]/))&&(this.strength=this.strongLabel,this.newPassword.match(/[!|#|$|%|-|_|=|\+|<|>]+/)?this.updateNewPasswordIconAndLabel("/img/passwordStrength/strong.gif",this.strength,"pscStrong",this.strongAltText,this.strengthSpecialCharStrong):this.updateNewPasswordIconAndLabel("/img/passwordStrength/strong.gif",this.strength,
"pscStrong",this.strongAltText,this.strengthStrong))};
ChangePassword.prototype.passwordVerify=function(){document.getElementById(ChangePasswordConstants.pNEW_PASSWORD_CONFIRMATION_ELEM).value==this.newPasswordUntrimmed&&""!==this.newPassword&&this.strength!=this.weakLabel?this.updateIcon(ChangePasswordConstants.pNEW_PASSWORD_CONFIRMATION_ICON_ELEM,UserContext.getUrl("/img/msg_icons/confirm16.gif"),LC.getLabel("Images","password_verify_alt")):this.updateIcon(ChangePasswordConstants.pNEW_PASSWORD_CONFIRMATION_ICON_ELEM,UserContext.getUrl("/img/s.gif"),
LC.getLabel("Images","blank_alt"))};
ChangePassword.prototype.answerVerify=function(){if(document.getElementById(ChangePasswordConstants.pANSWER_ELEM)&&document.getElementById(ChangePasswordConstants.pANSWER_ERROR_ELEM)){var a=document.getElementById(ChangePasswordConstants.pANSWER_ELEM).value;this.answerCannotContainPassword&&(-1!=a.toLowerCase().indexOf(this.newPassword.toLowerCase())&&""!==this.newPassword?(this.updateIcon(ChangePasswordConstants.pANSWER_ICON_ELEM,UserContext.getUrl("/img/msg_icons/error16.gif"),LC.getLabel("Password",
"SecretAnswerContainsPassword")),this.updateLabel(ChangePasswordConstants.pANSWER_ERROR_ELEM,LC.getLabel("Password","SecretAnswerContainsPassword"),void 0)):(this.updateIcon(ChangePasswordConstants.pANSWER_ICON_ELEM,UserContext.getUrl("/img/s.gif"),LC.getLabel("Images","blank_alt")),this.updateLabel(ChangePasswordConstants.pANSWER_ERROR_ELEM,"",void 0)))}};ChangePassword.prototype.updateIcon=function(a,b,c){if(a=document.getElementById(a))a.innerHTML="\x3cimg src \x3d '"+b+"' alt \x3d '"+c+"'\x3e\x3c/img\x3e"};
ChangePassword.prototype.updateLabel=function(a,b,c){if(a=document.getElementById(a))a.innerHTML=b,c&&(a.setAttribute("class",c),a.setAttribute("className",c))};ChangePassword.prototype.cleanUpErrorMessages=function(){for(var a=this.getElementsByClassNameWorkaroundForIE("div","errorMsg"),b=a.length;0<b;)b--,a[b].parentNode.removeChild(a[b])};
ChangePassword.prototype.getElementsByClassNameWorkaroundForIE=function(a,b){var c=document.getElementsByTagName(a),d=[],f=document.all?"className":"class";for(j=i=0;i<c.length;i++){var e=c[i].getAttribute(f);!e&&document.all&&(e=c[i].getAttribute("class"));e&&e==b&&(d[j]=c[i],j++)}return d};ChangePassword.prototype.setStyleText=function(a,b){a&&(a.style.setAttribute?a.style.setAttribute("cssText",b):a.setAttribute("style",b))};
function AdvCurrencyEnable(){}
AdvCurrencyEnable.checkSaveButton=function(a){(a?document.getElementById(AdvancedCurrencyEnable.pENABLE).checked:!document.getElementById(AdvancedCurrencyEnable.pENABLE).checked)?(document.getElementsByName(AdvancedCurrencyEnable.enableButton)[0].className="btn",document.getElementsByName(AdvancedCurrencyEnable.enableButton)[0].disabled=!1):(document.getElementsByName(AdvancedCurrencyEnable.enableButton)[0].className="btnDisabled",document.getElementsByName(AdvancedCurrencyEnable.enableButton)[0].disabled=!0)};
function ForecastRoleUser(){}
ForecastRoleUser.checkDisplayAllowSharing=function(){var a=document.getElementById(ForecastRoleUser.pUSER);""===a.options[a.selectedIndex].value?(document.getElementsByName(ForecastRoleUser.pCAN_SHARE)[0].disabled=!0,document.getElementsByName(ForecastRoleUser.pCAN_SHARE)[1].disabled=!0,document.getElementById(ForecastRoleUser.FORECAST_SHARE_RADIO).style.visibility="hidden"):(document.getElementsByName(ForecastRoleUser.pCAN_SHARE)[0].disabled=!1,document.getElementsByName(ForecastRoleUser.pCAN_SHARE)[1].disabled=!1,
document.getElementById(ForecastRoleUser.FORECAST_SHARE_RADIO).style.visibility="visible")};ForecastRoleUser.confirmRemoveShares=function(a){var b=document.getElementById(ForecastRoleUser.pUSER);return""!==b.options[b.selectedIndex].value||!a||window.confirm(LC.getLabel("ForecastSharingPref","confirmAssignNoMgr"))};
function FctSettingsPage(){}function FctShareDialog(){}FctSettingsPage.fctShareFormSubmit=!1;FctShareDialog.allowMgrShare="0";
FctSettingsPage.submitCheck=function(a,b){if(validateForm()){FctSettingsPage.fctShareFormSubmit=b==document.getElementById(ForecastSettings.pFORECAST_SHARING).checked;if(FctSettingsPage.fctShareFormSubmit)return!0;openPopupFocus(a,"fctSharingDialog",300,500,"height\x3d350,width\x3d600,location\x3dno,dependent\x3dno,resizable\x3dno,toolbar\x3dno,status\x3dyes,directories\x3dno,menubar\x3dno,scrollbars\x3dno",!0,!0,!0)}return!1};
FctShareDialog.checkSaveButton=function(a){(a?document.getElementById(ForecastSharingPrefPopup.DISABLE_CHECKBOX).checked:document.getElementsByName(ForecastSharingPrefPopup.CAN_SHARE_RADIO)[0].checked||document.getElementsByName(ForecastSharingPrefPopup.CAN_SHARE_RADIO)[1].checked)?(document.getElementsByName("save")[0].className="btn",document.getElementsByName("save")[0].disabled=!1,document.getElementsByName("save")[0].onclick=function(){FctShareDialog.saveResult(!0)},a||(FctShareDialog.allowMgrShare=
document.getElementsByName(ForecastSharingPrefPopup.CAN_SHARE_RADIO)[1].checked?"1":"0")):(document.getElementsByName("save")[0].className="btnDisabled",document.getElementsByName("save")[0].disabled=!0)};FctShareDialog.saveResult=function(a){a&&window.opener.FctSettingsPage.submit(FctShareDialog.allowMgrShare);window.close()};
FctSettingsPage.submit=function(a){var b=new QueryString;document.getElementById(ForecastSettings.pALLOW_FM_SHARING).value=a;b.add(EditPageConstants.pSAVE,"Save");document.forms[EditPageConstants.pEDIT_PAGE].action+=b.toString();document.forms[EditPageConstants.pEDIT_PAGE].submit()};
var ContentSettingsPage=function(){};ContentSettingsPage.toggleContentPrefs=function(a,b){document.getElementById(a).style.display=b.checked?"block":"none"};
var TagSettingsPage=function(){};TagSettingsPage.toggleTags=function(a,b){document.getElementById(a).style.display=b.checked?"block":"none"};
UserInterfaceUI.toggleCalendarPrefs=function(){var a=Sfdc.get(UserInterfaceUI.pNEW_LIST_VIEW_NAME),b=Sfdc.get(UserInterfaceUI.pDRAG_AND_DROP_ON_CALENDAR_NAME),d=Sfdc.get(UserInterfaceUI.pCLICK_AND_CREATE_ON_CALENDAR_NAME),c=Sfdc.get(UserInterfaceUI.pINLINE_SCHEDULING_NAME),e=Sfdc.get(UserInterfaceUI.pINLINE_SCHEDULING_NAME_MESSAGE);b.checked?(d.disabled=!1,d.checked?(c.disabled=!1,e.className=c.checked&&!(null!==a&&a.checked)?"message infoM4 twoindent":"hideblock"):(c.disabled=!0,c.checked=!1,e.className=
"hideblock")):(d.disabled=!0,d.checked=!1,c.disabled=!0,c.checked=!1,e.className="hideblock")};UserInterfaceUI.toggleAlohaSkin=function(a){var b=Sfdc.get(UserInterfaceUI.pALOHA_SKIN).checked;a&&UserInterfaceUI.showChatterThing(b);a=Sfdc.get("useSetupV2");b?(UserInterfaceUI.showAlohaDialog(),a&&(a.disabled=!1,a.checked=a.attributes["data-initialvalue"]&&"true"===a.attributes["data-initialvalue"].value)):a&&(a.disabled=!0,a.checked=!1)};UserInterfaceUI.alohaDialog=null;
UserInterfaceUI.showAlohaDialog=function(){if(!UserInterfaceUI.alohaDialog){var a=Dialogs.types.WARN;UserInterfaceUI.alohaDialog=Dialogs.createDialog({id:"alohaWarningDialog",title:LC.getLabel("UserInterfaceUI","AlohaWarningTitle"),message:Sfdc.get("alohaWarningContent").innerHTML,backgroundClass:a.backgroundClass,contentClass:a.contentClass,iconClass:a.iconClass,iconAlt:a.getIconAlt(),actions:[function(){}],actionLabels:[LC.getLabel("Buttons","ok")]},!0);UserInterfaceUI.alohaDialog.setWidth(560)}UserInterfaceUI.alohaDialog.show()};
UserInterfaceUI.showChatterThing=function(a){var b=Sfdc.get(UserInterfaceUI.pALOHA_CHATTER_MSG);b&&(b.style.display=a?"none":"block")};UserInterfaceUI.toggleSpellChecker=function(){var a=Sfdc.get(UserInterfaceUI.pSPELL_CHECKER_ENABLED_NAME),b=Sfdc.get(UserInterfaceUI.pSPELL_CHECKER_ACTIVITIES_NAME);a.checked?b.disabled=!1:(b.checked=!1,b.disabled=!0)};
UserInterfaceUI.toggleS1Desktop=function(){var a=Sfdc.get(UserInterfaceUI.pS1_DESKTOP_ENABLED_NAME);Sfdc.get(UserInterfaceUI.pS1_USE_ALOHA_NAME).disabled=a.checked?!1:!0};

//# sourceMappingURL=/javascript/1420712686000/sfdc/source/Setup.js.map
