var widgetVersion=184.36;var baseURL,baseSfdcUrl,contentDomainUrl,canvas_doc,canvas_window,controllerInitData,reverseName=false,popOut_UMPSWidget=false,actualUmpsDomain,popOut_ChatSubspaceId,umpsSubdomain,jshtml_loc,max_subdomains=5,_api_Caller_Source,loadProgress=0,rtlLnaguage=false;(function(){var S=function(c,b){var a=document.createElement("script");
a.type="text/javascript";if(a.readyState){a.onreadystatechange=function(){if(a.readyState=="loaded"||a.readyState=="complete"){a.onreadystatechange=null;if(b&&typeof b=="function"){b()}}}}else{a.onload=function(){if(b&&typeof b=="function"){b()}}}a.src=baseURL+P+c;document.getElementsByTagName("head")[0].appendChild(a)
};var J=function(){K("var umpsdoPageReload=function(){document.location.href = document.location.href;}")};var E=function(){var a='var umpsHttpGateWay=function(d){var g=function(){if(window.XMLHttpRequest){return new window.XMLHttpRequest()}else{try{return new ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(j){}}return null};var h=function(m,l){if(!m){return}var k=[];for(var n in m){k.push(n+"="+encodeURIComponent(m[n]))}var j=(l?"?":"")+k.join("&");return j};var a=d.url;var b=g();var f="";var c=a;if(d.data&&d.method=="POST"){f=h(d.data,false)}if(d.data&&d.method==="GET"){f=h(d.data,a.indexOf("?")===-1);c=a+f}b.open(d.method,c,true);if(d.headers){for(key in d.headers){try{if(d.headers.hasOwnProperty(key)){b.setRequestHeader(key,d.headers[key])}}catch(e){alert(e)}}}var i=b.send(f);b.onreadystatechange=function(){if(b.readyState===4){var j=b.status;if(j>=200&&j<300||j===304){d.success(b.responseText)}else{d.failure(b.responseText)}d.success=d.failure=d.beforerequest=null}}};';
K(a)};var K=function(b){var a=parent.parent.document.createElement("script");a.type="text/javascript";a.language="javascript";a.text=b;parent.parent.document.body.appendChild(a)};var I=function(){Jiffy.measure("Done","PreLoading");Jiffy.mark("CompleteBootstrap");if(presence.View.PopOutWidget.active){if(popOut_ChatSubspaceId){Jiffy.mark("CompleteBootstrapChatWindow")
}else{Jiffy.mark("CompleteBootstrapRoster")}}var c=parent.parent.document.createElement("div");c.id="presence_widget";c.className="presence_chat_widget";if(!(canvas_window.umps_config.isChatUiEnabled&&canvas_window.umps_config.isChatUiEnabled=="false")){parent.parent.document.body.appendChild(c)}presence.config.App="webmessenger";
presence.View.init();StorageManager.init();presence.Controller.init(controllerInitData);var a=new Date().getTime();presence.log("loadScript: "+(a-F),"info");try{E();J()}catch(b){presence.log("Exception in exporting HttpGateway to parent page="+b,"error")}umpsxdomain.receiveMessage(function(d){var f=d.data;
var e=JSON.parse(f);if(e.originCheck){window.originCheck(e.originCheck)}else{presence.EventManager.trigger(e.uuid,e,true,"api")}},actualUmpsDomain,document.getElementById("api_iframe").contentWindow)};var G=function(){if(H>=O){I()}else{S(Q[H]+"?cflag="+widgetVersion,G)}H++};var N=function(){var b=window.navigator.userAgent;
var a=b.indexOf("MSIE ");if(a>0){return parseInt(b.substring(a+5,b.indexOf(".",a)))}else{return 0}};canvas_doc=parent.parent.document;canvas_window=parent.parent;baseURL=canvas_window.umps_config.umpsUrl;baseSfdcUrl=canvas_window.umps_config.baseSfdcUrl;contentDomainUrl=canvas_window.umps_config.contentDomain;
var ae=canvas_window.umps_config.sfdcVersion;umpsWidgetPath=canvas_window.umps_config.umpsWidgetPath;var P="/umps/UMPSWidget/";if((ae&&ae!=null)&&(umpsWidgetPath&&umpsWidgetPath!=null)){P="/umps/"+umpsWidgetPath+"/"}var Y=(canvas_window.umps_config.randomMask&&!canvas_window.umps_config.popOut)?canvas_window.Sfdc.String.decryptXOR(canvas_window.umps_config.xoredSessionId,canvas_window.umps_config.randomMask):canvas_window.umps_config.sessionId;
var af=canvas_window.umps_config.userId;var ac=canvas_window.umps_config.orgId;controllerInitData={sid:Y,objectId:af,orgId:ac};var L=canvas_window.name.split("|");if(L[0]!="umps"){canvas_window.name="umps|"}L=canvas_window.name.split("|");if(canvas_window.umps_config.subDomain){umpsSubdomain=canvas_window.umps_config.subDomain
}else{if(L.length>2){umpsSubdomain=L[2].replace(/ /g,"")}else{umpsSubdomain=Math.floor(Math.random()*max_subdomains);canvas_window.name=canvas_window.name+"|"+umpsSubdomain+"|"}}var U=baseURL.split("://",2);actualUmpsDomain=U[0]+"://"+umpsSubdomain+"."+U[1];if(document.addEventListener){canvas_doc.addEventListener("keydown",function(a){if(typeof a.preventDefault!="function"){return
}if(a.keyCode==27){a.preventDefault()}},false)}if(canvas_window.umps_config.popOut){popOut_UMPSWidget=true}if(canvas_window.umps_config.chatSubspaceId){popOut_ChatSubspaceId=canvas_window.umps_config.chatSubspaceId}var Z=N();var T="en_US";var aa=["en_US","fr","ar","bg","cs","da","de","el","es","es_MX","fi","hu","in","it","iw","ja","ko","nl_NL","no","pl","pt_BR","ro","ru","sv","th","tr","uk","vi","zh_CN","zh_TW"];
var V=["ar","iw"];var ad=false;var W="umps-min";if(canvas_window.umps_config.userLanguage){T=canvas_window.umps_config.userLanguage}if(canvas_window.umps_config.localeStyle&&canvas_window.umps_config.localeStyle=="1"){reverseName=true}for(var l in aa){if(aa[l]==T){ad=true;break}}for(var R in V){if(V[R]==T){rtlLnaguage=true;
break}}if(!ad){T="en_US"}var Q=new Array("js/dist/"+W+".js","js/locales/"+T+".js");var O=Q.length,H=0;var F=new Date().getTime();var M=function(){var b=parent.parent.document.createElement("link");b.type="text/css";b.rel="stylesheet";b.href=baseURL+P+"css/presence_css.css?cflag="+widgetVersion;parent.parent.document.body.appendChild(b);
if(popOut_UMPSWidget){var a=parent.parent.document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href=baseURL+P+"css/presence_css_popout.css?cflag="+widgetVersion;parent.parent.document.body.appendChild(a)}if(rtlLnaguage){var c=parent.parent.document.createElement("link");c.type="text/css";
c.rel="stylesheet";c.href=baseURL+P+"css/presence_css_rtl.css?cflag="+widgetVersion;parent.parent.document.body.appendChild(c)}};var ab=function(){S("js/jiffy.js?cflag=1",function(){Jiffy.mark("PreLoading");G()})};if(Z==0||Z>7||canvas_window.document.readyState=="complete"){M();loadProgress++}else{canvas_window.attachEvent("onload",function(){M();
loadProgress++;if(loadProgress>1&&Z==7){ab()}})}var X=document.createElement("IFRAME");X.id="api_iframe";X.name="api_iframe";jshtml_loc=P+"_js.html?cflag="+widgetVersion+"&order=2&parentUrl="+window.location.protocol+"//"+window.location.host+"&connectUrl="+baseSfdcUrl;X.src=actualUmpsDomain+jshtml_loc;
X.frameborder=0;if(X.attachEvent){X.attachEvent("onload",function(){loadProgress++;if(loadProgress>1||Z==0||Z>7){ab()}})}else{X.onload=function(){loadProgress++;if(loadProgress>1||Z==0||Z>7){ab()}}}window.originCheck=function(a){if(canvas_window.retryDone){return}canvas_window.retryDone=true;if(a!=actualUmpsDomain){window.location.href=window.location.href
}};if(document.readyState=="complete"){document.body.appendChild(X)}else{window.onload=function(){document.body.appendChild(X)}}}());