(function(j){var i={};var q=function(){var v=/(opera)(?:.*version)?[ \/]([\w.]+)/;var u=navigator.userAgent;u=u.toLowerCase();var t=v.exec(u)||[];return t.length!=0};var m,o,f=1,h,l={},r=10,n=false,g=0,s=0,k="addEventListener",b,c,e,a,d=window.postMessage&&!q();i.postMessage=function(t,v,u){t=typeof t==="string"?t:encodeURIComponent(t);
u=u||parent;if(d){u.postMessage(t,v)}else{f++;l[f]={target:u,prefix:"#"+f+"&",message:t};umpsxdomain.setWindowName(f)}};i.setWindowName=function(u){if(l[u-1]){return}var t=l[u];if(t){if(window.name!=""){umpsxdomain.readWindowname()}t.target.name=t.prefix+s+"|"+t.message}};var p=function(t){t=parseInt(t);
if(l[t]){delete l[t];umpsxdomain.setWindowName(t+1)}};i.readWindowname=function(){var x=window.name,v=/^#?\d+&/;if(x!==o&&v.test(x)){window.name="";o=x;var t=x.indexOf("&"),u=x.indexOf("|"),w=x.substring(1,t);g=x.substring(t+1,u);if(w=="0"){p(g)}else{a.name="#0&"+w+"|";s=w;p(g);e({data:x.substring(u+1,x.length)})
}}clearTimeout(m);m=window.setTimeout(function(){umpsxdomain.readWindowname()},r)};i.receiveMessage=b=function(v,u,t){if(d){if(v){h&&b();h=function(x){if(typeof u==="string"&&x.origin!==u){var w=JSON.parse(x.data);if(w&&w.originCheck){return v({data:JSON.stringify({originCheck:w.originCheck})})}return false
}v(x)}}if(window[k]){window[v?k:"removeEventListener"]("message",h,false)}else{window[v?"attachEvent":"detachEvent"]("onmessage",h)}}else{if(v&&t){e=v;a=t;umpsxdomain.readWindowname()}}};j.umpsxdomain=i})(window);(function(c){var f=function(){};var h=function(k,i,j){if(!k){return}if(k.addEventListener){k.addEventListener(i,j,false)
}else{if(k.attachEvent){k.attachEvent("on"+i,j)}}};var b=function(k,i,j){if(!k){return}if(k.removeEventListener){k.removeEventListener(i,j,false)}else{if(k.detachEvent){k.detachEvent("on"+i,j)}}};var d=function(){var j=null;try{j=new XMLHttpRequest();return function(){return new XMLHttpRequest()}}catch(i){}if(!j){try{j=new ActiveXObject("Msxml2.XMLHTTP");
return function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(i){}}if(!j){try{j=new ActiveXObject("Microsoft.XMLHTTP");return function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(i){}}if(!j){return function(){return null}}}();var e=function(l,k){if(!l){return null}var j=[];for(var m in l){j.push(m+"="+encodeURIComponent(l[m]))
}var i=(k?"?":"")+j.join("&");return i};var g=function(j,i){var l=i.headers||{};l.Accept="text/javascript, text/html, application/xml, application/json, text/xml, */*";l["X-Requested-With"]=l["X-Requested-With"]||"XMLHttpRequest";if(i.data){l["Content-type"]=l["Content-type"]||"application/x-www-form-urlencoded";
for(var k in l){l.hasOwnProperty(k)&&j.setRequestHeader(k,l[k])}}};var a=function(l){var i=l.url;var j=d();if(j){try{var n="";var k=i+"?cflag="+new Date().getTime();if(l.data&&(l.method=="POST"||l.method=="PUT")){n=e(l.data,false)}if(l.data&&(l.method==="GET"||l.method==="DELETE")){n=e(l.data,false);
k=k+"&"+n;n=null}if(l.timeout){var p=setTimeout(function(){j.abort()},l.timeout)}var o=function(){j.abort()};h(window,"beforeunload",o);j.open(l.method,k,true);g(j,l);var q=j.send(n);j.onreadystatechange=function(){if(j.readyState===4){if(p){clearTimeout(p)}b(window,"beforeunload",o);try{var r=j.status;
if(r>=200&&r<300||r===304){l.success(j)}else{if(r===0){l.failure({status:-5,reason:"Error in server-"+r})}else{l.failure({status:-4,reason:"non 200 response from server",response:j.responseText})}}}catch(s){l.failure({status:-2,reason:"exception in onreadystatechange"})}l.success=l.failure=l.beforerequest=null;
j.onreadystatechange=f;j=null}}}catch(m){l.failure({status:-3,reason:"exception in making XHR call"})}}else{l.failure({status:-1,reason:"XHR object not able to create"})}return j};c.umpsAjax=a})(this);(function(b){var a=new (function(){var l=!!{}.hasOwnProperty,h=Object.prototype.toString,c=function(){var m=null;
return function(){if(m===null){m=b.USE_NATIVE_JSON&&window.JSON&&JSON.toString()=="[object JSON]"}return m}}(),i=function(m){return m<10?"0"+m:m},k=function(m){return m},q=function(x){if(!o(x)||x===null){return"null"}else{if(n(x)){return g(x)}else{if(p(x)){return s(x)}else{if(d(x)){return r(x)}else{if(typeof x=="number"){return isFinite(x)?String(x):"null"
}else{if(e(x)){return String(x)}else{var t=["{"],m,w,u;for(w in x){if(!x.getElementsByTagName){if(!l||x.hasOwnProperty(w)){u=x[w];switch(typeof u){case"undefined":case"function":case"unknown":break;default:if(m){t.push(",")}t.push(q(w),":",u===null?"null":q(u));m=true}}}}t.push("}");return t.join("")
}}}}}}},j={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},r=function(m){if(/["\\\x00-\x1f]/.test(m)){return'"'+m.replace(/([\x00-\x1f\\"])/g,function(u,t){var v=j[t];if(v){return v}v=t.charCodeAt();return"\\u00"+Math.floor(v/16).toString(16)+(v%16).toString(16)})+'"'}return'"'+m+'"'
},g=function(y){var u=["["],m,x,t=y.length,w;for(x=0;x<t;x+=1){w=y[x];switch(typeof w){case"undefined":case"function":case"unknown":break;default:if(m){u.push(",")}u.push(w===null?"null":a.encode(w));m=true}}u.push("]");return u.join("")},s=function(m){return'"'+m.getFullYear()+"-"+i(m.getMonth()+1)+"-"+i(m.getDate())+"T"+i(m.getHours())+":"+i(m.getMinutes())+":"+i(m.getSeconds())+'"'
},n=("isArray" in Array)?Array.isArray:function(m){return h.call(m)==="[object Array]"},p=function(m){return h.call(m)==="[object Date]"},f=(typeof document!=="undefined"&&typeof document.getElementsByTagName("body")==="function")?function(m){return h.call(m)==="[object Function]"}:function(m){return typeof m==="function"
},d=function(m){return typeof m==="string"},e=function(m){return typeof m==="boolean"},o=function(m){return typeof m!=="undefined"};this.encode=function(){var m;return function(t){if(!m){m=c()?JSON.stringify:q}return m(t)}}();this.decode=function(){var m;return function(t){if(!m){m=c()?JSON.parse:k}return m(t)
}}()})()})(window);(function(a){var b=function(g){var d;var e;var f=this;f.uuid=g;this.sendRequest=function(i,n,l,k,m){if(!m){m={}}if(!l){l={}}m.connectUrl=connectUrl||sfdcUrl;var j=umpsAjax({url:i,method:n,data:l,success:function(o){c(o)},failure:function(o){h(o)},headers:m,timeout:k});b.reqs[f.uuid]=j
};var c=function(i){var k={};k.uuid=f.uuid;if(!i.responseText){k.status=0}else{var j=JSON.parse(i.responseText);k.data=j}presence.EventManager.trigger(k.uuid,k,true,"api");delete b.reqs[f.uuid]};var h=function(j){var k=j.response?j.response:"{}";var i=JSON.parse(k);var l={};l.uuid=f.uuid;l.status=j.status;
l.response=i;presence.EventManager.trigger(l.uuid,l,true,"api");delete b.reqs[f.uuid]}};b.reqs=new Array();b.decodeRes=function(d){try{return JSON.parse(d)}catch(c){return{}}};b.getXhrById=function(c){return b.reqs[c]};a.RequestGateway=b})(window);(function(b){var a=function(g){var d;var e;var f=this;
f.uuid=g;this.sendRequest=function(i,n,l,k,m){if(!m){m={}}if(!l){l={}}m.connectUrl=connectUrl||sfdcUrl;var j=umpsAjax({url:i,method:n,data:l,success:function(o){c(o)},failure:function(o){h(o)},headers:m,timeout:k});a.reqs[f.uuid]=j};var c=function(i){if(i.responseText){postToChild('{"uuid":"'+f.uuid+'","data":'+i.responseText+"}")
}else{postToChild('{"uuid":"'+f.uuid+'","status":0}')}delete a.reqs[f.uuid]};var h=function(i){if(i.response){postToChild('{"uuid":"'+f.uuid+'","status":'+i.status+',"response":'+i.response+"}")}else{postToChild('{"uuid":"'+f.uuid+'","status":'+i.status+"}")}delete a.reqs[f.uuid]}};a.reqs=new Array();
a.decodeRes=function(d){try{return JSON.parse(d)}catch(c){return{}}};a.getXhrById=function(c){return a.reqs[c]};b.HttpGateway=a})(window);